import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffdad7",
        "surface-dim": "#dcd9d9",
        "tertiary-fixed-dim": "#e2bebf",
        "text-body": "#555555",
        "on-error-container": "#93000a",
        "surface-container-high": "#eae7e7",
        tertiary: "#715556",
        "secondary-fixed-dim": "#ffb3ae",
        "surface-bright": "#fcf9f8",
        "on-primary-container": "#fffbff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5c0009",
        error: "#ba1a1a",
        "navbar-dark": "#111111",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#8b6d6e",
        "error-container": "#ffdad6",
        "surface-neutral-alt": "#F8F8F8",
        primary: "#b1212b",
        surface: "#fcf9f8",
        "on-tertiary-container": "#fffbff",
        "outline-variant": "#e2bebc",
        "divider-tint": "#FBD5D6",
        "inverse-surface": "#313030",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#930015",
        background: "#fcf9f8",
        "primary-fixed": "#ffdad7",
        "on-primary": "#ffffff",
        "on-background": "#1c1b1b",
        "action-whatsapp-hover": "#1EBE5D",
        "on-surface": "#1c1b1b",
        "on-tertiary-fixed": "#2a1617",
        "on-primary-fixed-variant": "#920119",
        "inverse-primary": "#ffb3af",
        "surface-container": "#f0eded",
        "surface-canvas": "#FFFFFF",
        "bracket-border": "#F65456",
        "text-muted": "#777777",
        "primary-container": "#d43b40",
        secondary: "#b81f27",
        "tertiary-fixed": "#ffdadb",
        "surface-tint": "#b5242d",
        "action-whatsapp": "#25D366",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#5a4041",
        "on-secondary-fixed": "#410004",
        "secondary-container": "#fe5453",
        "on-surface-variant": "#5a403f",
        outline: "#8e706e",
        "on-primary-fixed": "#410005",
        "accent-gold": "#FFD700",
        "surface-tint-light": "#FFF0F0",
        "surface-container-highest": "#e5e2e1",
        "surface-container-low": "#f6f3f2",
        "navbar-black": "#0B0B0B",
        "primary-fixed-dim": "#ffb3af",
        "inverse-on-surface": "#f3f0ef",
        "surface-variant": "#e5e2e1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "gutter-sm": "1rem",
        "space-xl": "2.5rem",
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "space-2xl": "4rem",
        "space-lg": "1.5rem",
        "space-3xl": "6rem",
        "space-md": "1rem",
        "margin-md": "3rem",
        "gutter-lg": "2rem",
        "margin-lg": "5rem",
        margin: "1.5rem",
        "space-2xs": "0.25rem",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        heading: ["var(--font-plus-jakarta)", "sans-serif"],
        "display-hero": ["var(--font-plus-jakarta)", "sans-serif"],
        "display-hero-mobile": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-xl": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-xl-mobile": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta)", "sans-serif"],
        "stat-number": ["var(--font-plus-jakarta)", "sans-serif"],
        "stat-number-mobile": ["var(--font-plus-jakarta)", "sans-serif"],
        "label-nav": ["var(--font-plus-jakarta)", "sans-serif"],
        "cta-pill": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "label-meta": ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
